const WORDS = {
    Description: {
        pt_br: 'Descrição',
        cs: 'Popis',
        en: 'Description',
        fr: 'Description',
        de: 'Beschreibung',
        hu: 'Leírás',
        it: 'Descrizione',
        ja: 'ユニット紹介',
        ko: '설명',
        pl: 'Opis',
        ru: 'Описание',
        es: 'Descripción',
        tr: 'Açıklama',
        uk: 'Опис',
        ['zh-hans']: '说明',
        ['zh-hant']: '說明',
    },
    Abilities: {
        pt_br: '',
        cs: '',
        en: 'Abilities',
        fr: 'Capacités',
        de: '',
        hu: '',
        it: '',
        ja: 'Abilities',
        ko: '',
        pl: 'Umiejętności',
        ru: 'Способности',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '能力',
        ['zh-hant']: '',
    },
    Specialist_hero: {
        pt_br: '',
        cs: '',
        en: 'Specialist Hero',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '特长英雄',
        ['zh-hant']: '',
    },
    Category_Units: {
        pt_br: '',
        cs: '',
        en: 'Units',
        fr: 'Unités',
        de: '',
        hu: '',
        it: '',
        ja: 'Units/ja',
        ko: '',
        pl: 'Jednostki',
        ru: 'Существа',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_hero_skills: {
        pt_br: 'Habilidades de Herói',
        cs: 'Schopnosti hrdiny',
        en: 'Hero Skills',
        fr: 'Compétences de héros',
        de: 'Heldenfähigkeiten',
        hu: 'A hősök képességei',
        it: "Abilità dell'eroe",
        ja: 'ヒーローのスキル',
        ko: '영웅 스킬',
        pl: 'Umiejętności bohatera',
        ru: 'Навыки героев',
        es: 'Habilidades del héroe',
        tr: 'Kahraman Becerileri',
        uk: 'Уміння героя',
        ['zh-hans']: '英雄技能',
        ['zh-hant']: '英雄技能',
    },
    Strategy: {
        pt_br: '',
        cs: '',
        en: 'Strategy',
        fr: 'Stratégie',
        de: '',
        hu: '',
        it: '',
        ja: 'Strategy',
        ko: '',
        pl: 'Strategia',
        ru: 'Стратегия',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '策略',
        ['zh-hant']: '',
    },
    Strategy_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add it...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '还没有内容，或许你可以补充一下……？',
        ['zh-hant']: '',
    },
    Laws: {
        pt_br: 'Leis',
        cs: 'Zákony',
        en: 'Laws',
        fr: 'Lois',
        de: 'Gesetze',
        hu: 'Törvénykezés',
        it: 'Leggi',
        ja: '法',
        ko: '법률',
        pl: 'Prawa',
        ru: 'Законы',
        es: 'Leyes',
        tr: 'Kanunlar',
        uk: 'Закони',
        ['zh-hans']: '律法',
        ['zh-hant']: '律法',
    },
    Laws_text: {
        pt_br: '',
        cs: '',
        en: 'This unit is affected by the following Faction [[Laws]]:',
        fr: 'Cette unité est affectée par les [[Laws/fr|lois]] de faction suivantes:',
        de: '',
        hu: '',
        it: '',
        ja: 'This unit is affected by the following Faction [[Laws/ja|Laws]]:',
        ko: '',
        pl: 'Na tę jednostkę wpływają następujące [[Laws/pl|Prawa Frakcji]]:',
        ru: 'На это существо действуют следующие [[Законы|законы]] фракции:',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: 'This unit is affected by the following Faction [[Laws/zh-hans]]:',
        ['zh-hant']: '',
    },
    Specialist: {
        pt_br: '',
        cs: '',
        en: 'Specialist hero',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Related_pages: {
        pt_br: '',
        cs: '',
        en: 'Related pages',
        fr: 'Voir aussi',
        de: '',
        hu: '',
        it: '',
        ja: '関連項目',
        ko: '',
        pl: 'Zobacz też',
        ru: 'См. также',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '参见',
        ['zh-hant']: '',
    },
    Stinger_main: {
        pt_br: '',
        cs: '',
        en: '',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '#1 to ulepszona [[Units/pl|jednostka]] tieru #2 frakcji #3.',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Stinger_dwelling: {
        pt_br: '',
        cs: '',
        en: '',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: ' Można ją rekrutować z #1.',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Stinger_is_base: {
        pt_br: '',
        cs: '',
        en: '',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jednostka może być ulepszona do #1 lub #2.',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Stinger_is_upgraded: {
        pt_br: '',
        cs: '',
        en: '',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jest to jedna z ulepszonych wersji #1, drugą jest #2.',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_human_Units: {
        pt_br: '',
        cs: '',
        en: 'Temple Units',
        fr: 'Unités du Temple',
        de: '',
        hu: '',
        it: '',
        ja: 'Temple Units/ja',
        ko: '',
        pl: 'Jednostki Świątyni',
        ru: 'Существа Храма',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_undead_Units: {
        pt_br: '',
        cs: '',
        en: 'Necropolis Units',
        fr: 'Unités du Nécropole',
        de: '',
        hu: '',
        it: '',
        ja: 'Necropolis Units/ja',
        ko: '',
        pl: 'Jednostki Nekropolii',
        ru: 'Существа Некрополя',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_nature_Units: {
        pt_br: '',
        cs: '',
        en: 'Grove Units',
        fr: 'Unités du Bosquet',
        de: '',
        hu: '',
        it: '',
        ja: 'Grove Units/ja',
        ko: '',
        pl: 'Jednostki Sylwanu',
        ru: 'Существа Рощи',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_demon_Units: {
        pt_br: '',
        cs: '',
        en: 'Hive Units',
        fr: 'Unités de la Ruche',
        de: '',
        hu: '',
        it: '',
        ja: 'Hive Units/ja',
        ko: '',
        pl: 'Jednostki Roju',
        ru: 'Существа Роя',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_unfrozen_Units: {
        pt_br: '',
        cs: '',
        en: 'Schism Units',
        fr: 'Unités du Schisme',
        de: '',
        hu: '',
        it: '',
        ja: 'Schism Units/ja',
        ko: '',
        pl: 'Jednostki Schizmy',
        ru: 'Существа Раскола',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_dungeon_Units: {
        pt_br: '',
        cs: '',
        en: 'Dungeon Units',
        fr: 'Unités du Donjon',
        de: '',
        hu: '',
        it: '',
        ja: 'Dungeon Units/ja',
        ko: '',
        pl: 'Jednostki Lochu',
        ru: 'Существа Подземель',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_neutral_Units: {
        pt_br: '',
        cs: '',
        en: 'Neutral Units',
        fr: 'Unités neutres',
        de: '',
        hu: '',
        it: '',
        ja: 'Neutral Units/ja',
        ko: '',
        pl: 'Jednostki Neutralne',
        ru: 'Нейтральные существа',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_hero_classes: {
        pt_br: '',
        cs: '',
        en: 'Hero Classes',
        fr: 'Hero Classes/fr',
        de: '',
        hu: '',
        it: '',
        ja: 'Hero Classes/ja',
        ko: '',
        pl: 'Klasa Bohatera',
        ru: 'Классы героев',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: 'Hero Classes/zh-hans',
        ['zh-hant']: '',
    },
    Spells: {
        pt_br: 'Feitiços',
        cs: 'Kouzla',
        en: 'Spells',
        fr: 'Sorts',
        de: 'Zaubersprüche',
        hu: 'Varázslatok',
        it: 'Incantesimi',
        ja: '呪文',
        ko: '주문',
        pl: 'Zaklęcia',
        ru: 'Заклинания',
        es: 'Hechizos',
        tr: 'Büyüler',
        uk: 'Чари',
        ['zh-hans']: '法术',
        ['zh-hant']: '法術',
    },
    Interactions: {
        pt_br: '',
        cs: '',
        en: 'Interactions and synergies',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Interactions_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add some...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Heroes: {
        pt_br: 'Heróis',
        cs: 'Hrdinové',
        en: 'Heroes',
        fr: 'Héros',
        de: 'Helden',
        hu: 'Hősök',
        it: 'Eroi',
        ja: 'ヒーロー',
        ko: '영웅',
        pl: 'Bohaterowie',
        ru: 'Герои',
        es: 'Héroes',
        tr: 'Kahramanlar',
        uk: 'Герої',
        ['zh-hans']: '英雄',
        ['zh-hant']: '英雄',
    },
    HeroClass_intro_might: {
        pt_br: '',
        cs: '',
        en: 'The @name is the Might Hero of the @faction faction. Their Magic counterpart is the @other.',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '@name to Bohater Mocy frakcji @faction. Jego odpowiednikiem jest Bohater Magii @other.',
        ru: '@name — герой-воин фракции @faction. Героем-магом в той же фракции является @other.',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    HeroClass_intro_magic: {
        pt_br: '',
        cs: '',
        en: 'The @name is the Magic Hero of the @faction faction. Their Might counterpart is the @other.',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '@name  to Bohater Magii frakcji @faction.  Jego odpowiednikiem jest Bohater Mocy @other.',
        ru: '@name — герой-маг фракции @faction. Героем-воином в той же фракции является @other.',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Elite_classes: {
        pt_br: '',
        cs: '',
        en: 'Elite Classes',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Klasy Elitarne',
        ru: 'Элитный класс',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Elite_text: {
        pt_br: '',
        cs: '',
        en: 'The @name can get promoted into one of the following Elite Classes if they learn all the required skills at Expert level:',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Bohater @name mogą awansować do jednej z następujących klas elitarnych, jeśli nauczą się wszystkich wymaganych umiejętności na poziomie eksperta:',
        ru: '@name может получить один из элитных классов, если соберёт особую комбинацию экспертных навыков:',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Skills: {
        pt_br: 'Habilidades',
        cs: 'Schopnosti',
        en: 'Skills',
        fr: 'Compétences',
        de: 'Fähigkeiten',
        hu: 'Képességek',
        it: 'Abilità',
        ja: 'スキル',
        ko: '스킬',
        pl: 'Umiejętności',
        ru: 'Навыки',
        es: 'Habilidades',
        tr: 'Beceriler',
        uk: 'Уміння',
        ['zh-hans']: '技能',
        ['zh-hant']: '技能',
    },
    HeroClass_Skills_might: {
        pt_br: '',
        cs: '',
        en: 'As a Might Hero, the @name has good chances of learning Might-related skills, and can learn the Might-exclusive skill @skill.',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jako Bohater Mocy @name ma duże szanse na naukę umiejętności związanych z Mocą i może nauczyć się umiejętności @skill, która jest wyłączną umiejętnością Mocy.',
        ru: 'Как герой-воин, @name чаще получает навыки, усиливающие армию, а также может изучить навык @skill, доступный исключительно воинам.',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    HeroClass_Skills_magic: {
        pt_br: '',
        cs: '',
        en: 'As a Magic Hero, the @name has good chances of learning Magic-related skills, and can learn the Magic-exclusive skill @skill.',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jako Bohater Magii, @name ma duże szanse na naukę umiejętności związanych z magią i może nauczyć się umiejętności @skill, która jest wyłączną umiejętnością Magii.',
        ru: 'Как герой-маг, @name чаще получает навыки, усиливающие заклинания, а также может изучить навык @skill, доступный исключительно магам.',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    HeroClass_Skills_generic: {
        pt_br: '',
        cs: '',
        en: 'A @name has the following chances of getting new, Basic-level skills offered on level-up:',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '@name ma następujące szanse na zdobycie nowych umiejętności na poziomie podstawowym oferowanych po awansie na wyższy poziom:',
        ru: 'При повышении уровня @name получает базовый навык со следующей вероятностью:',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Levels: {
        pt_br: '',
        cs: '',
        en: 'Levels',
        fr: 'Niveaux de compétence',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Poziomy umiejętności',
        ru: 'Уровни навыков',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Chances: {
        pt_br: '',
        cs: '',
        en: 'Chances',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Skill_synergies: {
        pt_br: '',
        cs: '',
        en: 'Skill synergies',
        fr: 'Synergies de compétences',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '', // needed
        ru: 'Синергия навыков',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    synergiesText: {
        pt_br: '',
        cs: '',
        en: 'Knowing @skillName will give the following benefits to other subskills:',
        fr: 'Connaître la @skillName apporte les avantages suivants aux autres compétences secondaires :',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Znajomość umiejętności @skillName zapewni następujące korzyści innym podumiejętnościom:',
        ru: 'Владение навыком «@skillName» даёт следующие преимущества для других поднавыков:',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Artifact_effects: {
        pt_br: '',
        cs: '',
        en: 'Artifact effects',
        fr: "Effets d'artéfact",
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '', // needed
        ru: 'Эффекты артефактов',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
};

export default WORDS;
