import fs from 'node:fs';
import suggestFileNames from '../helpers/suggestFileNames.js';
import handleFreshHero from './handleFreshHero.js';
import handleOldHero from './handleOldHero.js';
import getTranslations from '../helpers/getTranslations.js';
import generatePayloads from '../helpers/generatePayloads.js';

// =====================================================================================================================
//  D E C L A R A T I O N S
// =====================================================================================================================
const TRANSLATIONS = {
    Heroes: {
        pt_br: 'Heróis',
        cs: 'Hrdinové',
        en: 'Heroes',
        fr: 'Héros',
        de: 'Helden',
        hu: 'Hősök',
        it: 'Eroi',
        ja: 'ヒーロー',
        ko: '영웅',
        pl: 'Bohaterowie',
        ru: 'Герои',
        es: 'Héroes',
        tr: 'Kahramanlar',
        uk: 'Герої',
        ['zh-hans']: '英雄',
        ['zh-hant']: '英雄',
    },
    Specialization: {
        pt_br: '',
        cs: '',
        en: 'Specialization',
        fr: 'Spécialisation',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Specjalizacja',
        ru: 'Специализация',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Biography: {
        pt_br: '',
        cs: '',
        en: 'Biography',
        fr: 'Biographie',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Biografia',
        ru: 'Биография',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Strategy: {
        pt_br: '',
        cs: '',
        en: 'Strategy',
        fr: 'Stratégie',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Strategia',
        ru: 'Стратегия',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Strategy_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add it...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
};

const TARGET_LANGUAGES = new Set([
    'en',
    // 'zh-hans',
    // 'es',
    'fr',
    // 'pt_br',
    'ru',
    // 'de',
    'ja',
    // 'tr',
    // 'ko',
    // 'it',
    // 'zh-hant',
    'pl',
    // 'uk',
    // 'hu',
    // 'cs',
]);

const IDS = [
    // 'demon_hero_1',
    // 'demon_hero_10',
    // 'demon_hero_11',
    // 'demon_hero_12',
    // 'demon_hero_13',
    // 'demon_hero_14',
    // 'demon_hero_15',
    // 'demon_hero_16',
    // 'demon_hero_17',
    // 'demon_hero_18',
    // 'demon_hero_2',
    // 'demon_hero_3',
    // 'demon_hero_4',
    // 'demon_hero_5',
    // 'demon_hero_6',
    // 'demon_hero_7',
    // 'demon_hero_8',
    // 'demon_hero_9',
    // 'dungeon_hero_1',
    // 'dungeon_hero_10',
    // 'dungeon_hero_11',
    // 'dungeon_hero_12',
    // 'dungeon_hero_13',
    // 'dungeon_hero_14',
    // 'dungeon_hero_15',
    // 'dungeon_hero_16',
    // 'dungeon_hero_17',
    // 'dungeon_hero_18',
    // 'dungeon_hero_2',
    // 'dungeon_hero_3',
    // 'dungeon_hero_4',
    // 'dungeon_hero_5',
    // 'dungeon_hero_6',
    // 'dungeon_hero_7',
    // 'dungeon_hero_8',
    // 'dungeon_hero_9',
    // 'human_hero_1',
    // 'human_hero_10',
    // 'human_hero_11',
    // 'human_hero_12',
    // 'human_hero_13',
    // 'human_hero_14',
    // 'human_hero_15',
    // 'human_hero_16',
    // 'human_hero_17',
    // 'human_hero_18',
    // 'human_hero_2',
    // 'human_hero_3',
    // 'human_hero_4',
    // 'human_hero_5',
    // 'human_hero_6',
    // 'human_hero_7',
    // 'human_hero_8',
    // 'human_hero_9',
    // 'nature_hero_1',
    // 'nature_hero_10',
    // 'nature_hero_11',
    // 'nature_hero_12',
    // 'nature_hero_13',
    // 'nature_hero_14',
    // 'nature_hero_15',
    // 'nature_hero_16',
    // 'nature_hero_17',
    // 'nature_hero_18',
    // 'nature_hero_2',
    // 'nature_hero_3',
    // 'nature_hero_4',
    // 'nature_hero_5',
    // 'nature_hero_6',
    // 'nature_hero_7',
    // 'nature_hero_8',
    // 'nature_hero_9',
    // 'necro_hero_1',
    // 'necro_hero_10',
    // 'necro_hero_11',
    // 'necro_hero_12',
    // 'necro_hero_13',
    // 'necro_hero_14',
    // 'necro_hero_15',
    // 'necro_hero_16',
    // 'necro_hero_17',
    // 'necro_hero_18',
    // 'necro_hero_2',
    // 'necro_hero_3',
    // 'necro_hero_4',
    // 'necro_hero_5',
    // 'necro_hero_6',
    // 'necro_hero_7',
    // 'necro_hero_8',
    // 'necro_hero_9',
    // 'unfrozen_hero_1',
    // 'unfrozen_hero_10',
    // 'unfrozen_hero_11',
    // 'unfrozen_hero_12',
    // 'unfrozen_hero_13',
    // 'unfrozen_hero_14',
    // 'unfrozen_hero_15',
    // 'unfrozen_hero_16',
    // 'unfrozen_hero_17',
    // 'unfrozen_hero_18',
    // 'unfrozen_hero_2',
    // 'unfrozen_hero_3',
    // 'unfrozen_hero_4',
    // 'unfrozen_hero_5',
    // 'unfrozen_hero_6',
    // 'unfrozen_hero_7',
    // 'unfrozen_hero_8',
    // 'unfrozen_hero_9',
];

// =====================================================================================================================
//  P U B L I C
// =====================================================================================================================
/**
 *
 */
async function hero() {
    let skirmishHeroes = getTranslations('/Hero~', 'hero', /tutorial|campaign|cm_fun/);
    // skirmishHeroes = skirmishHeroes.filter((item) => IDS.includes(item.target_id));
    const fileNames = suggestFileNames(skirmishHeroes);
    const payloads = generatePayloads({
        items: skirmishHeroes,
        fileNames,
        languages: TARGET_LANGUAGES,
        translations: TRANSLATIONS,
        handleFresh: handleFreshHero,
        handleOld: handleOldHero,
    });
    // console.log('payloads:', payloads);
    for (const {path, content} of payloads) {
        content && fs.writeFileSync(path, content);
    }
}

// =====================================================================================================================
//  R U N
// =====================================================================================================================
await hero();
