const WORDS = {
    Abilities: {
        pt_br: '',
        cs: '',
        en: 'Abilities',
        fr: 'Capacités',
        de: '',
        hu: '',
        it: '',
        ja: 'Abilities',
        ko: '',
        pl: 'Umiejętności',
        ru: 'Способности',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '能力',
        ['zh-hant']: '',
    },
    Category_Units: {
        pt_br: '',
        cs: '',
        en: 'Units',
        fr: 'Unités',
        de: '',
        hu: '',
        it: '',
        ja: 'Units/ja',
        ko: '',
        pl: 'Jednostki',
        ru: 'Существа',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Strategy: {
        pt_br: '',
        cs: '',
        en: 'Strategy',
        fr: 'Stratégie',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Strategia',
        ru: 'Стратегия',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Strategy_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add it...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Laws: {
        pt_br: 'Leis',
        cs: 'Zákony',
        en: 'Laws',
        fr: 'Lois',
        de: 'Gesetze',
        hu: 'Törvénykezés',
        it: 'Leggi',
        ja: '法',
        ko: '법률',
        pl: 'Prawa',
        ru: 'Законы',
        es: 'Leyes',
        tr: 'Kanunlar',
        uk: 'Закони',
        ['zh-hans']: '律法',
        ['zh-hant']: '律法',
    },
    Laws_text: {
        pt_br: '',
        cs: '',
        en: 'This unit is affected by the following Faction [[Laws]]:',
        fr: 'Cette unité est affectée par les [[Laws/fr|lois]] de faction suivantes:',
        de: '',
        hu: '',
        it: '',
        ja: 'This unit is affected by the following Faction [[Laws/ja|Laws]]:',
        ko: '',
        pl: 'This unit is affected by the following Faction [[Laws/pl|Laws]]:',
        ru: 'На это существо действуют следующие [[Законы|законы]] фракции:',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Specialist: {
        pt_br: '',
        cs: '',
        en: 'Specialist hero',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_human_Units: {
        pt_br: '',
        cs: '',
        en: 'Temple Units',
        fr: 'Unités du Temple',
        de: '',
        hu: '',
        it: '',
        ja: 'Temple Units/ja',
        ko: '',
        pl: 'Jednostki Świątyni',
        ru: 'Существа Храма',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_undead_Units: {
        pt_br: '',
        cs: '',
        en: 'Necropolis Units',
        fr: 'Unités du Nécropole',
        de: '',
        hu: '',
        it: '',
        ja: 'Necropolis Units/ja',
        ko: '',
        pl: 'Jednostki Nekropolii',
        ru: 'Существа Некрополя',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_nature_Units: {
        pt_br: '',
        cs: '',
        en: 'Grove Units',
        fr: 'Unités du Bosquet',
        de: '',
        hu: '',
        it: '',
        ja: 'Grove Units/ja',
        ko: '',
        pl: 'Jednostki Sylwanu',
        ru: 'Существа Рощи',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_demon_Units: {
        pt_br: '',
        cs: '',
        en: 'Hive Units',
        fr: 'Unités de la Ruche',
        de: '',
        hu: '',
        it: '',
        ja: 'Hive Units/ja',
        ko: '',
        pl: 'Jednostki Roju',
        ru: 'Существа Роя',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_unfrozen_Units: {
        pt_br: '',
        cs: '',
        en: 'Schism Units',
        fr: 'Unités du Schisme',
        de: '',
        hu: '',
        it: '',
        ja: 'Schism Units/ja',
        ko: '',
        pl: 'Jednostki Schizmy',
        ru: 'Существа Раскола',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_dungeon_Units: {
        pt_br: '',
        cs: '',
        en: 'Dungeon Units',
        fr: 'Unités du Donjon',
        de: '',
        hu: '',
        it: '',
        ja: 'Dungeon Units/ja',
        ko: '',
        pl: 'Jednostki Lochu',
        ru: 'Существа Подземель',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Category_neutral_Units: {
        pt_br: '',
        cs: '',
        en: 'Neutral Units',
        fr: 'Unités neutres',
        de: '',
        hu: '',
        it: '',
        ja: 'Neutral Units/ja',
        ko: '',
        pl: 'Jednostki Neutralne',
        ru: 'Нейтральные существа',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
};

export default WORDS;
