// =====================================================================================================================
//  P U B L I C
// =====================================================================================================================
/**
 *
 */
function buildInfoBox({lang, id, masterfulFragment}) {
    // TODO: preserve old masterful text and not use the one generated by us
    const masterfulText = masterfulFragment?.[lang] || '';
    const masterful = masterfulFragment ? `|masterful=${masterfulText}` : '';
    return `{{Template:SpellInfobox|lang=${lang}|id=${id}${masterful}}}`;
}

// =====================================================================================================================
//  E X P O R T
// =====================================================================================================================
export default buildInfoBox;
