const WORDS = {
    Spells: {
        pt_br: 'Feitiços',
        cs: 'Kouzla',
        en: 'Spells',
        fr: 'Sorts',
        de: 'Zaubersprüche',
        hu: 'Varázslatok',
        it: 'Incantesimi',
        ja: '呪文',
        ko: '주문',
        pl: 'Zaklęcia',
        ru: 'Заклинания',
        es: 'Hechizos',
        tr: 'Büyüler',
        uk: 'Чари',
        ['zh-hans']: '法术',
        ['zh-hant']: '法術',
    },
    Strategy: {
        pt_br: '',
        cs: '',
        en: 'Strategy',
        fr: 'Stratégie',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Strategia',
        ru: 'Стратегия',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Strategy_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add it...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Interactions: {
        pt_br: '',
        cs: '',
        en: 'Interactions and synergies',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Interactions_text: {
        pt_br: '',
        cs: '',
        en: 'Nothing yet. Maybe you can add some...?',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: 'Jeszcze nic. Może możesz to dodać...?',
        ru: 'Здесь пока ничего нет. Возможно, вы сможете это исправить?',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Specialist_hero: {
        pt_br: '',
        cs: '',
        en: 'Specialist hero',
        fr: '',
        de: '',
        hu: '',
        it: '',
        ja: '',
        ko: '',
        pl: '',
        ru: '',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '',
        ['zh-hant']: '',
    },
    Related_pages: {
        pt_br: '',
        cs: '',
        en: 'Related pages',
        fr: 'Voir aussi',
        de: '',
        hu: '',
        it: '',
        ja: '関連項目',
        ko: '',
        pl: 'Zobacz też',
        ru: 'См. также',
        es: '',
        tr: '',
        uk: '',
        ['zh-hans']: '参见',
        ['zh-hant']: '',
    },
};

export default WORDS;
